// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyrfjaabteoohicxcmnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cmZqYWFidGVvb2hpY3hjbW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTQxMDQsImV4cCI6MjA2NTA3MDEwNH0.AHvdJWmUiFmz5_PrDe_l-6SYDU3nOvHJV_e7ReBNdkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);